### ISSUE TITLE
Git workflow

### ISSUE THREAD

**Issue by DM-Berger** [Ashcoding1/soccer_analytics#1]
We need to decide on how to best collaborate. Neither of us are experts, but in my experience, for working closely with just one or two people on a small project, a good workflow is to use [_personal branching_](https://about.gitlab.com/topics/version-control/what-is-git-workflow/). 

However, as this is also something (eventually) public-facing, we also don't necessarily want `main` to just immediately merge in changes of each personal branch. Whatever is on `main` should, IMO, ideally be something that is minimally-working and without bugs. In this case, I find having a `develop` branch (as per the [Gitflow workflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow)) is convenient. 

Essentially, the workflow is like this:

1. move fast and break things in personal branches (`derek` and `shoaib`/`abdullah`)
    - here, regular pushing, even of broken code, is encouraged, even just for saving / backing up work
    - if you want to make a temporary personal feature branch, you can branch this _off of the personal branch_
       - e.g. I am on `derek` and want to implement a bar-graph display, so I `git checkout -b bargraph`, do a bunch of work there, and when it is working, `git rebase -i derek`
2. when a feature is implemented to some satisfactory level update the `develop` branch in various ways
    - In the past, I have been loose with this, usually squash-merging if there are a lot of commits on the `personal` branch
    - alternately, if desired, the owner of the personal branch could interactive rebase down to a single commit / small number of clean commits, and this could be merged / rebased in full
    - also alternately, a personal feature branch can be locally interactive rebased, pushed, and then the personal feature branch can be merged to develop
    - the idea is that personal branches are allowed to be as messy as we want, but that `develop` gets cleaner versions of personal work merged in only
    - merges / rebasing personal branches or personal feature branches into / onto `develop` _**does not**_ require code review
3. Periodically, merge (or squash merge) `develop` into `main` with proper PRs and code review (and CI?)
   - in our case, "code review" is both of us reviewing our own code

Basically, without personal branching, one hesitates to push (since that means conflicts for others), and this is a recipe for losing work (or not being able to revert /compare to earlier commits where something was working). And without `develop`, one would have to try to join collaborative work right on `main`, which is going to leave a very messy history overall. There is also a small risk of mucking up `main` when doing this. Also, later this helps separate development and deployment. 

In addition, as long as everyone *regularly* pushes to their personal branches, other team members can see where things are going by checking out each each other's branches. You can avoid messy conflicts later like this in small teams ("Oh, better not touch that file for now, XXX is making a bunch of fixes there"). 

Anyway, I am 100% open to any other strategies / suggestions here!

**Comment by Ashcoding1** [comment]
The workflow above looks good and will be followed.
