### ISSUE TITLE
Code Testing: Unit/Integration Tests, Coverage, Frameworks

### ISSUE THREAD

**Issue by DM-Berger** [Ashcoding1/soccer_analytics#3]
We want to test crucial / difficult code paths, and things that are testable but where it is easy to make mistakes. I really doubt we should aim for high coverage or worry about coverage stats, because it isn't worth the time, and is mostly "make-work" anyway. It would be cool to learn some browser-automation testing, but I also don't think there is time for that. 

So mostly this comes down to choosing some frameworks for writing and running unit tests. It seems like we don't really have to make any choices here:

- **Python**
  - normally I would say go with just `pytest`, but [**Django recommends `unittest`**](https://docs.djangoproject.com/en/4.0/topics/testing/), and so I suggest we go with that
- **JS/TS**
  - Here, Jest is still the most popular framework, and is probably best for with React

If you are good with `unittest` and Jest, then we can close this issue and get those configured when we actually need to test things.

**Comment by Ashcoding1** [comment]
Looks good to me.
