### ISSUE TITLE
Python / TS / Node / npm versioning, environments, libraries, etc.

### ISSUE THREAD

**Issue by DM-Berger** [Ashcoding1/soccer_analytics#6]
We need to be sure our builds / testing are reproducible and work across machines / environments. For Python, we could use Poetry, or just `pyenv` + `venv`, to start. I wouldn't recommend Poetry, it seems to have a lot of lurking issues. Later, if this is really an issue, it is also probably easier to setup a Docker container with `pyenv` + `venv` inside, if we really are having trouble. 

The main thing then is to decide on a major Python version (3.8, 3.9, 3.10). Django [supports 3.10](https://docs.djangoproject.com/en/4.0/faq/install/), so I recommend we take advantage of the massive speedups and fun new features (e.g. pattern matching) and **use Python 3.10**. We could just try the newest version 3.10.4 for now: we can always downgrade if some library doesn't support this. 

The other thing is node version (for TypeScript compiler). This is _probably_ less important than figuring out Python issues, so we can handle that as we get there. But most likely we want the latest versions, and then can pin them from there.

**Comment by Ashcoding1** [comment]
Looks good to me.
